[package]
name = "roboteur-rust-client"
version = "0.0.1-alpha"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_socketio = "0.2.4"
serde_json = "1.0.68"
reqwest = "0.11.5"